const axios = require('axios').default

// Funtion used to fetch flight data from the server
async function fetchFlightData() {
    try {
        const response = await axios.get(
            'https://aircraft.freeth.kiwi/VirtualRadar/AircraftList.json'
        )
        // console.log(response.data.acList)
        return response
    } catch (error) {
        console.error(error)
        return null
    }
}

// Funtion to pull Flight data out following the fetchFlightData() function
async function getAllFlights() {
    try {
        const flights = {}
        ;(await fetchFlightData(flights)).data.acList.forEach((rawflight) => {
            // Key the data based on the Aircraft Registration Number, else using the Server Flight ID.
            if (rawflight.Reg == null) {
                flights[rawflight.Id] = rawflight
            } else if (rawflight.Reg != null) {
                flights[rawflight.Reg] = rawflight
            }
        })
        // console.log(flights)
        // console.log(Object.keys(flight))
        return flights
    } catch (error) {
        console.error(error)
        return null
    }
}

// Funtion to get a specific flight based on the Aircraft Registration Number
// Based off the list generated by the getAllFlights() function, if no Aircraft Registration Number is not known USE the Server Flight ID
async function getFlightDetails(aircraftrego) {
    try {
        const foundFlight = {}
        const allFlights = await getAllFlights().then()
        if (allFlights[aircraftrego]) {
            // console.log('FOUND VIA REGO')
            // console.log(allFlights[aircraftrego])
            foundFlight[aircraftrego] = allFlights[aircraftrego]
        } else {
            console.log('FLIGHT NOT FOUND')
        }
        return foundFlight
    } catch (error) {
        console.error(error)
        return null
    }
}

export default getAllFlights
export { getAllFlights, getFlightDetails }
